[workspace]
members = [
    "core/amend",
    "core/apply",
    "core/blame",
    "core/branch",
    "core/clock",
    "core/commit",
    "core/diff",
    "core/email",
    "core/flow",
    "core/graph",
    "core/init",
    "core/log",
    "core/patch",
    "core/rebase",
    "core/reset",
    "core/resolve",
    "core/restore",
    "core/revert",
    "core/rule",
    "core/snap",
    "core/status",
    "core/web",
    "database/db",
    "database/storage",
    "remote/clone",
    "remote/fetch",
    "remote/issues",
    "remote/mr",
    "remote/news",
    "remote/pr",
    "remote/pull",
    "remote/push",
    "repo",
    "teams/boards/board",
    "teams/communication/chat",
    "teams/communication/comment",
    "teams/communication/contact",
    "teams/developer/code",
    "teams/developer/customize",
    "teams/developer/gui",
    "teams/developer/key",
    "teams/developer/search",
    "teams/developer/stats",
    "teams/developer/submit",
    "teams/issues/bug",
    "teams/manager/analys",
    "teams/manager/assign",
    "teams/manager/perms",
    "teams/manager/predict",
    "teams/manager/progress",
    "teams/manager/remember",
    "teams/manager/review",
    "teams/manager/teams",
    "teams/manager/todo",
    "teams/manager/track",
    "teams/payment/fact",
    "teams/payment/pay",
    "teams/project/client",
    "teams/project/due",
    "teams/project/owner",
    "workflows/iso",
    "workflows/visualize",
    "workflows/work",
]
resolver = "2"
