[package]
name = "kairo-commit"
version = "0.0.0"
edition = "2021"
description = ""
license = "GPL-3.0-or-later"
repository = "https://github.com/otechdo/kairo/tree/main/src/core/kairo-commit"
readme = "README.md"

[dependencies]
chrono = "0.4.38"
inquire = "0.7.5"
