[package]
name = "kairo-code"
version = "0.0.0"
edition = "2021"
description = ""
license = "GPL-3.0-or-later"
repository = "https://github.com/otechdo/kairo/tree/main/src/teams/developer/kairo-code"
readme = "README.md"

[dependencies]
