[package]
name = "kairo-search"
version = "0.0.0"
edition = "2021"
description = ""
license = "GPL-3.0-or-later"
repository = "hhttps://github.com/otechdo/kairo/tree/main/src/teams/developer/kairo-search/"
readme = "README.md"

[dependencies]
